### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by flamendless** [MartyMaro/scrale#1]
Is the sample snippet for STI and Gamera in load or draw?

Also, how bout using it with STI and hump.camera? 

Thanks

**Comment by martin-braun** [comment]
Hey, sorry for the late reply.

The sample snippet for STI and Gamera is in the load function, since the map for STI and the Gamera objects are only initialized once. Tutorials for STI and Gamera show this, you update and draw those on the appropriate functions later.

I haven't work with hump.camera until now, so I cannot give a proper example for it.
